services:
  touraxis_micro:
    build:
      context: .
      dockerfile: ./apps/touraxis-micro/Dockerfile
      target: development
    command: npm run start:dev touraxis-micro
    env_file:
      - .env
    depends_on:
      - postgis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4001:4001'

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - .env
    depends_on:
      - postgis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  tasks:
    build:
      context: .
      dockerfile: ./apps/tasks/Dockerfile
      target: development
    command: npm run start:dev tasks
    env_file:
      - .env
    depends_on:
      - postgis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  nats:
    image: nats:latest
    ports:
      - '4222:4222'

  postgis:
    container_name: touraxis_micro_postgis_container
    image: postgis/postgis
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'

  pgadmin4:
    container_name: touraxis_micro_pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
